path:
  # data_dir: './PANDA_data/'
  data_dir: '../input/prostate-cancer-grade-assessment'
  df_train: 'train.csv'
  df_test:  'test.csv'
  df_submit: 'sample_submission.csv'

  # model_dir: './'
  model_dir: '../input/pretrained'
  train_image_folder: 'train_images'
  test_image_folder: 'test_images'

  pretrained_model: 'train_isup_parallel_with_BN_best_fold0.pth'

name:
  enet_type: 'efficientnet-b0'

values:
  image_size: 1536
  tile_size: 256
  n_tiles: 36
  crop_size: 256
  tiff_layer: 1
  max_rescale: 19660800

learning:
  batch_size: 12
  num_workers: 12
  # out_dim: 6
  out_dim: 5

device:
  gpu_id: 0

DEBUG: False